# Generated by Django 4.2.6 on 2023-10-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL('''
                          Insert into store_collection (title) 
                          values ('collection1')''',
                          """
                            Delete from store_collection
                            where title ='collection1'
""")
    ]
