# Generated by Django 4.2.6 on 2023-11-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
