# Generated by Django 4.2.6 on 2023-11-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cacel_order', 'Can cancel order')]},
        ),
    ]
